make:
	$(MAKE) -C cmd
	$(MAKE) -C exec

clean:
	$(MAKE) clean -C cmd
	$(MAKE) clean -C exec

install:
	$(MAKE) install -C cmd
	$(MAKE) install -C exec

uninstall:
	$(MAKE) uninstall -C cmd
	$(MAKE) uninstall -C exec

all:
	$(MAKE) all -C cmd
	$(MAKE) all -C exec
