make:
	$(MAKE) -C cmd
	$(MAKE) -C path

clean:
	$(MAKE) clean -C cmd
	$(MAKE) clean -C path

install:
	$(MAKE) install -C cmd
	$(MAKE) install -C path

all:
	$(MAKE) all -C cmd
	$(MAKE) all -C path

uninstall:
	$(MAKE) uninstall -C cmd
	$(MAKE) uninstall -C path
