make:
	$(MAKE) $(target) -C cmd
	$(MAKE) $(target) -C path

clean: target = clean
clean: make

install: target = install
install: make

all: target = all
all: make

uninstall: target = uninstall
uninstall: make
